### PR TITLE
Re-export `jsonrpsee` so users don't have to match the version

### PR DESCRIPTION
**Pull request by hrxi**

### CODE REVIEW

**Comment by hrxi** [comment]
Otherwise we get failures like this: https://github.com/nimiq/core-rs-albatross/pull/2231.

**Review by jsdanielh — APPROVED** [review]
Thanks! But `core-rs-albatross` should no longer use this fork. I'll be working on switching it back

**Comment by jsdanielh** [comment]
Pushed to upstream repo in https://github.com/nimiq-community/rust-client/commit/5e6f057a265564c214d66ac0316e4d362014c1c1.

**Comment by hrxi** [comment]
Thanks!

**Pull request merged**
